characters = {  
    sol: {
        name: "Sol Badguy",
        image: "https://www.dustloop.com/wiki/images/0/04/GGST_Sol_Badguy_Portrait.png",
        playstyle: "prepared",
        moral_system: "good",
        gender: "male",
        favourite: ["pressure"],
        important: ["all_rounder", "damage"],
        zoning: 0.0,
        rushdown: 1.0,
        oneplayer: "sometimes",
        range: ["close", "mid"],
        stance: "no",
        charge: "no",
        gameplan: ["risc", "frametrap"],
        setplay: "no",
        projectile: "limited",
        reversal: "meterless",
        resource: "no",
        vortex: "neutral",
        difficulty: "easy",
        design: "serious",
        archetype: "rushdown",
        score: 0
    },
    ky: {
        name: "Ky Kiske",
        image: "https://www.dustloop.com/wiki/images/2/21/GGST_Ky_Kiske_Portrait.png",
        playstyle: "prepared",
        moral_system: "good",
        gender: "male",
        favourite: ["neutral", "pressure"],
        important: ["all_rounder"],
        zoning: 0.5,
        rushdown: 0.5,
        oneplayer: "sometimes",
        range: ["mid", "all"],
        stance: "yes",
        charge: "no",
        gameplan: ["frametrap"],
        setplay: "oki",
        projectile: "standard",
        reversal: "meterless",
        resource: "no",
        vortex: "projectile",
        difficulty: "easy",
        design: "serious",
        archetype: "balanced",
        score: 0
    },
    may: {
        name: "May",
        image: "https://www.dustloop.com/wiki/images/0/0d/GGST_May_Portrait.png",
        playstyle: "rewarding",
        moral_system: "good",
        gender: "female",
        favourite: ["combos"],
        important: ["all_rounder", "damage"],
        zoning: 0.0,
        rushdown: 1.0,
        oneplayer: "yes",
        range: ["mid", "close"],
        stance: "no",
        charge: "yes",
        gameplan: ["grab", "highlow"],
        setplay: "no",
        projectile: "limited",
        reversal: "metered",
        resource: "no",
        vortex: "projectile",
        difficulty: "easy",
        design: "silly",
        archetype: "rushdown",
        score: 0
    },
    faust: {
        name: "Faust",
        image: "https://www.dustloop.com/wiki/images/f/ff/GGST_Faust_Portrait.png",
        playstyle: "specialist",
        moral_system: "neutral",
        gender: "male",
        favourite: ["neutral"],
        important: ["utility"],
        zoning: 1.0,
        rushdown: 0.0,
        oneplayer: "no",
        range: "long",
        stance: "no",
        charge: "no",
        gameplan: ["grab", "highlow"],
        setplay: ["oki", "neutral"],
        projectile: ["limited","special"],
        reversal: "metered",
        resource: "no",
        vortex: "projectile",
        difficulty: "hard",
        design: "mixed",
        archetype: "setplay",
        score: 0
    },
    millia: {
        name: "Millia Rage",
        image: "https://www.dustloop.com/wiki/images/a/ab/GGST_Millia_Rage_Portrait.png",
        playstyle: "specialist",
        moral_system: "neutral",
        gender: "female",
        favourite: ["mindgames", "neutral"],
        important: ["mobility", "utility"],
        zoning: 0.0,
        rushdown: 1.0,
        oneplayer: "yes",
        range: ["close", "mid"],
        stance: "no",
        charge: "no",
        gameplan: ["highlow", "leftright"],
        setplay: ["oki"],
        projectile: "limited",
        reversal: "metered",
        resource: "no",
        vortex: "lots",
        difficulty: "medium",
        design: "serious",
        archetype: "rushdown",
        score: 0
    },
    chipp: {
        name: "Chipp Zanuff",
        image: "https://www.dustloop.com/wiki/images/d/d3/GGST_Chipp_Zanuff_Portrait.png",
        playstyle: "prepared",
        moral_system: "good",
        gender: "male",
        favourite: ["pressure", "neutral"],
        important: ["mobility", "utility"],
        zoning: 0.0,
        rushdown: 1.0,
        oneplayer: "yes",
        range: "close",
        stance: "no",
        charge: "no",
        gameplan: ["highlow", "leftright"],
        setplay: ["no"],
        projectile: "limited",
        reversal: "meterless",
        resource: "no",
        vortex: "lots",
        difficulty: "medium",
        design: "mixed",
        archetype: "rushdown",
        score: 0
    },
    ino: {
        name: "I-No",
        image: "https://www.dustloop.com/wiki/images/a/a1/GGST_I-No_Portrait.png",
        playstyle: "rewarding",
        moral_system: "evil",
        gender: "female",
        favourite: ["mindgames", "pressure"],
        important: ["mobility"],
        zoning: 0.0,
        rushdown: 1.0,
        oneplayer: "yes",
        range: "close",
        stance: "no",
        charge: "no",
        gameplan: ["highlow"],
        setplay: ["neutral"],
        projectile: "standard",
        reversal: "metered",
        resource: "no",
        vortex: "lots",
        difficulty: "medium",
        design: "mixed",
        archetype: "rushdown",
        score: 0
    },
    axl: {
        name: "Axl Low",
        image: "https://www.dustloop.com/wiki/images/b/b7/GGST_Axl_Low_Portrait.png",
        playstyle: "specialist",
        moral_system: "neutral",
        gender: "male",
        favourite: ["neutral", "pressure"],
        important: ["damage", "utility"],
        zoning: 1.0,
        rushdown: 0.0,
        oneplayer: "no",
        range: ["mid", "long"],
        stance: "no",
        charge: "no",
        gameplan: ["frametrap", "risc"],
        setplay: ["neutral"],
        projectile: "special",
        reversal: "metered",
        resource: "no",
        vortex: "neutral",
        difficulty: "easy",
        design: "silly",
        archetype: "zoners",
        score: 0
    },
    zato: {
        name: "Zato-1",
        image: "https://www.dustloop.com/wiki/images/d/df/GGST_Zato-1_Portrait.png",
        playstyle: "rewarding",
        moral_system: "neutral",
        gender: "male",
        favourite: ["combos", "mindgames"],
        important: ["utility", "damage"],
        zoning: 0.25,
        rushdown: 0.75,
        oneplayer: "no",
        range: ["mid", "all"],
        stance: "yes",
        charge: "no",
        gameplan: ["risc", "grab"],
        setplay: ["neutral"],
        projectile: "limited",
        reversal: "metered",
        resource: ["meter","ammo"],
        vortex: "lots",
        difficulty: "hard",
        design: "mixed",
        archetype: "balanced",
        score: 0
    },
    pot: {
        name: "Potemkin",
        image: "https://www.dustloop.com/wiki/images/e/ec/GGST_Potemkin_Portrait.png",
        playstyle: "rewarding",
        moral_system: "neutral",
        gender: "male",
        favourite: ["pressure"],
        important: ["health", "damage"],
        zoning: 0.25,
        rushdown: 0.25,
        oneplayer: "no",
        range: ["close", "mid"],
        stance: "no",
        charge: ["sometimes", "yes"],
        gameplan: "grab",
        setplay: "no",
        projectile: "no",
        reversal: "metered",
        resource: "no",
        vortex: "neutral",
        difficulty: "medium",
        design: "silly",
        archetype: "grappler",
        score: 0
    },
    ramlethal: {
        name: "Ramlethal Valentine",
        image: "https://www.dustloop.com/wiki/images/f/fa/GGST_Ramlethal_Valentine_Portrait.png",
        playstyle: "rewarding",
        moral_system: "good",
        gender: "female",
        favourite: "pressure",
        important: ["all_rounder"],
        zoning: 0.50,
        rushdown: 0.50,
        oneplayer: "yes",
        range: ["mid", "long"],
        stance: "no",
        charge: "no",
        gameplan: ["highlow", "risc"],
        setplay: "no",
        projectile: "standard",
        reversal: "metered",
        resource: "ammo",
        vortex: "neutral",
        difficulty: "easy",
        design: "serious",
        archetype: "balanced",
        score: 0
    },
    leo: {
        name: "Leo Whitefang",
        image: "https://www.dustloop.com/wiki/images/f/f7/GGST_Leo_Whitefang_Portrait.png",
        playstyle: "rewarding",
        moral_system: "good",
        gender: "male",
        favourite: ["pressure", "mindgames"],
        important: ["damage", "health"],
        zoning: 0.0,
        rushdown: 1.0,
        oneplayer: "sometimes",
        range: "close",
        stance: "yes",
        charge: "yes",
        gameplan: ["highlow", "frametrap", "leftright"],
        setplay: "neutral",
        projectile: "standard",
        reversal: "meterless",
        resource: "no",
        vortex: "neutral",
        difficulty: "easy",
        design: "serious",
        archetype: "balanced",
        score: 0
    },
    anji: {
        name: "Anji Mito",
        image: "https://www.dustloop.com/wiki/images/5/5c/GGST_Anji_Mito_Portrait.png",
        playstyle: "specialist",
        moral_system: "neutral",
        gender: "male",
        favourite: ["pressure", "neutral"],
        important: ["all_rounder"],
        zoning: 0.25,
        rushdown: 0.75,
        oneplayer: "no",
        range: "mid",
        stance: "yes",
        charge: "no",
        gameplan: ["frametrap"],
        setplay: ["neutral", "oki"],
        projectile: "limited",
        reversal: "meterless",
        resource: "no",
        vortex: "projectile",
        difficulty: "easy",
        design: "serious",
        archetype: "balanced",
        score: 0
    },
    nago: {
        name: "Nagoriyuki",
        image: "https://www.dustloop.com/wiki/images/a/af/GGST_Nagoriyuki_Portrait.png",
        playstyle: "specialist",
        moral_system: "evil",
        gender: "male",
        favourite: ["pressure", "combos"],
        important: ["damage", "health"],
        zoning: 0.75,
        rushdown: 0.25,
        oneplayer: "no",
        range: ["mid", "long"],
        stance: "yes",
        charge: "no",
        gameplan: ["frametrap", "risc"],
        setplay: "no",
        projectile: "limited",
        reversal: "metered",
        resource: "meter",
        vortex: "neutral",
        difficulty: "easy",
        design: "serious",
        archetype: ["balanced", "zoners"],
        score: 0
    },
    goldlewis: {
        name: "Goldlewis Dickinson",
        image: "https://www.dustloop.com/wiki/images/7/7c/GGST_Goldlewis_Dickinson_Portrait.png",
        playstyle: "rewarding",
        moral_system: "good",
        gender: "male",
        favourite: ["pressure", "combos"],
        important: ["damage", "health"],
        zoning: 0.50,
        rushdown: 0.0,
        oneplayer: "no",
        range: ["close", "all"],
        stance: "no",
        charge: "no",
        gameplan: ["frametrap", "highlow"],
        setplay: ["neutral", "oki"],
        projectile: "special",
        reversal: "metered",
        resource: "meter",
        vortex: "neutral",
        difficulty: "hard",
        design: "serious",
        archetype: "balanced",
        score: 0
    },
    jacko: {
        name: "Jack-O’ Valentine",
        image: "https://www.dustloop.com/wiki/images/6/6f/GGST_Jack-O%27_Portrait.png",
        playstyle: "prepared",
        moral_system: "good",
        gender: "female",
        favourite: ["combos", "neutral"],
        important: "utility",
        zoning: 0.75,
        rushdown: 0.50,
        oneplayer: "no",
        range: "all",
        stance: "no",
        charge: "no",
        gameplan: ["frametrap", "risc"],
        setplay: ["neutral", "oki"],
        projectile: "special",
        reversal: "metered",
        resource: "meter",
        vortex: ["neutral", "projectile"],
        difficulty: "hard",
        design: "silly",
        archetype: "setplay",
        score: 0
    },
    chaos: {
        name: "Happy Chaos",
        image: "https://www.dustloop.com/wiki/images/c/c4/GGST_Happy_Chaos_Portrait.png",
        playstyle: "specialist",
        moral_system: "evil",
        gender: "male",
        favourite: ["pressure", "neutral"],
        important: ["damage", "utility"],
        zoning: 0.75,
        rushdown: 0.25,
        oneplayer: "yes",
        range: ["mid", "long"],
        stance: "yes",
        charge: "no",
        gameplan: ["risc"],
        setplay: "no",
        projectile: "special",
        reversal: "metered",
        resource: "ammo",
        vortex: "projectile",
        difficulty: "hard",
        design: "mixed",
        archetype: ["zoner", "setplay"],
        score: 0
    },
    baiken: {
        name: "Baiken",
        image: "https://www.dustloop.com/wiki/images/6/6e/GGST_Baiken_Portrait.png",
        playstyle: "prepared",
        moral_system: "neutral",
        gender: "female",
        favourite: ["pressure", "combos"],
        important: "all_rounder",
        zoning: 0.25,
        rushdown: 0.75,
        oneplayer: "sometimes",
        range: ["mid", "close"],
        stance: "no",
        charge: "no",
        gameplan: ["frametrap", "grab"],
        setplay: "no",
        projectile: "limited",
        reversal: "meterless",
        resource: "no",
        vortex: "lots",
        difficulty: "easy",
        design: "serious",
        archetype: "rushdown",
        score: 0
    },
    testament: {
        name: "Testament",
        image: "https://www.dustloop.com/wiki/images/thumb/b/ba/GGST_Testament_Portrait.png/790px-GGST_Testament_Portrait.png?20220320145752",
        playstyle: "specialist",
        moral_system: "neutral",
        gender: ["female", "male"],
        favourite: "neutral",
        important: ["utility", "mobility"],
        zoning: 1.0,
        rushdown: 0.0,
        oneplayer: "no",
        range: ["mid", "long"],
        stance: "no",
        charge: "no",
        gameplan: "highlow",
        setplay: "yes",
        projectile: "special",
        reversal: "metered",
        resource: "ammo",
        vortex: ["neutral", "projectile"],
        difficulty: "easy",
        design: "serious",
        archetype: "zoners",
        score: 0
    },
    bridget: {
        name: "Bridget",
        image: "https://www.dustloop.com/wiki/images/8/83/GGST_Bridget_Portrait.png",
        playstyle: "prepared",
        moral_system: "good",
        gender: "female",
        favourite: ["neutral", "combos"],
        important: ["mobility", "utility"],
        zoning: 0.75,
        rushdown: 0.25,
        oneplayer: "no",
        range: ["mid", "long"],
        stance: "no",
        charge: "no",
        gameplan: ["frametrap", "grab"],
        setplay: ["oki", "neutral"],
        projectile: "special",
        reversal: "meterless",
        resource: "no",
        vortex: ["neutral", "projectile"],
        difficulty: "easy",
        design: "silly",
        archetype: "zoners",
        score: 0
    },
    sin: {
        name: "Sin Kiske",
        image: "https://www.dustloop.com/wiki/images/8/8a/GGST_Sin_Kiske_Portrait.png",
        playstyle: "specialist",
        moral_system: "good",
        gender: "male",
        favourite: "pressure",
        important: ["all_rounder", "mobility"],
        zoning: 0.0,
        rushdown: 1.0,
        oneplayer: "yes",
        range: ["mid", "close"],
        stance: "no",
        charge: "no",
        gameplan: ["highlow", "frametrap"],
        setplay: "no",
        projectile: "no",
        reversal: "meterless",
        resource: "meter",
        vortex: "neutral",
        difficulty: "easy",
        design: "silly",
        archetype: "rushdown",
        score: 0
    },
    bedman: {
        name: "Bedman?",
        image: "https://www.dustloop.com/wiki/images/3/33/GGST_Bedman_Portrait.png",
        playstyle: "specialist",
        moral_system: "neutral",
        gender: "male",
        favourite: "combos",
        important: ["damage", "health"],
        zoning: 0.50,
        rushdown: 0.25,
        oneplayer: "no",
        range: "all",
        stance: "yes",
        charge: "no",
        gameplan: ["frametrap", "highlow"],
        setplay: "no",
        projectile: "standard",
        reversal: "metered",
        resource: "ammo",
        vortex: "neutral",
        difficulty: "hard",
        design: "silly",
        archetype: "balanced",
        score: 0
    },
    asuka: {
        name: "Asuka R. Kreutz",
        image: "https://www.dustloop.com/wiki/images/f/f7/GGST_Asuka_R_Portrait.png",
        playstyle: "prepared",
        moral_system: "neutral",
        gender: "male",
        favourite: ["pressure", "neutral"],
        important: ["all_rounder", "utility"],
        zoning: 0.75,
        rushdown: 0.0,
        oneplayer: "sometimes",
        range: ["mid", "long"],
        stance: "yes",
        charge: "no",
        gameplan: ["highlow", "frametrap"],
        setplay: "neutral",
        projectile: ["standard", "special"],
        reversal: "metered",
        resource: ["meter", "ammo"],
        vortex: "projectile",
        difficulty: "hard",
        design: "serious",
        archetype: ["zoners", "setplay"],
        score: 0
    },
    johnny: {
        name: "Johnny",
        image: "https://www.dustloop.com/wiki/images/3/3f/GGST_Johnny_Portrait.png",
        playstyle: "specialist",
        moral_system: "good",
        gender: "male",
        favourite: "neutral",
        important: ["mobility", "all_rounder"],
        zoning: 1.0,
        rushdown: 0.0,
        oneplayer: "yes",
        range: "mid",
        stance: "yes",
        charge: "no",
        gameplan: ["frametrap", "highlow"],
        setplay: "oki",
        projectile: "limited",
        reversal: "metered",
        resource: "no",
        vortex: ["neutral", "projectile"],
        difficulty: "easy",
        design: "serious",
        archetype: "zoners",
        score: 0
    },
    elphelt: {
        name: "Elphelt Valentine",
        image: "https://www.dustloop.com/wiki/images/6/6d/GGST_Elphelt_Valentine_Portrait.png",
        playstyle: "specialist",
        moral_system: "good",
        gender: "female",
        favourite: "pressure",
        important: ["damage", "mobility"],
        zoning: 0.25,
        rushdown: 1.0,
        oneplayer: "yes",
        range: "close",
        stance: "no",
        charge: "no",
        gameplan: ["frametrap", "highlow"],
        setplay: "no",
        projectile: "standard",
        reversal: "metered",
        resource: "no",
        vortex: "lots",
        difficulty: "good",
        design: "silly",
        archetype: "rushdown",
        score: 0
    },
    aba: {
        name: "A.B.A.",
        image: "https://www.dustloop.com/wiki/images/9/99/GGST_A.B.A_Portrait.png",
        playstyle: "specialist",
        moral_system: "neutral",
        gender: "female",
        favourite: "neutral",
        important: "damage",
        zoning: 0.0,
        rushdown: 1.0,
        oneplayer: "no",
        range: "close",
        stance: "yes",
        charge: "no",
        gameplan: "highlow",
        setplay: "no",
        projectile: "no",
        reversal: "metered",
        resource: "meter",
        vortex: "lots",
        difficulty: "medium",
        design: "serious",
        archetype: "rushdown",
        score: 0
    },
    slayer: {
        name: "Slayer",
        image: "https://www.dustloop.com/wiki/images/0/0a/GGST_Slayer_Portrait.png",
        playstyle: "specialist",
        moral_system: "neutral",
        gender: "male",
        favourite: ["pressure", "combos"],
        important: ["damage", "mobility"],
        zoning: 0.0,
        rushdown: 1.0,
        oneplayer: "sometimes",
        range: ["mid", "close"],
        stance: "no",
        charge: "no",
        gameplan: ["frametrap", "leftright"],
        setplay: "no",
        projectile: "no",
        reversal: "metered",
        resource: "no",
        vortex: "lots",
        difficulty: "easy",
        design: "serious",
        archetype: "rushdown",
        score: 0
    },
    easydizzy: {
        name: "Easy Dizzy",
        image: "https://www.dustloop.com/wiki/images/4/47/GGST_Queen_Dizzy_Portrait.png",
        playstyle: "specialist",
        moral_system: "good",
        gender: "female",
        favourite: "neutral",
        important: ["damage", "all_rounder"],
        zoning: 1.0,
        rushdown: 0.0,
        oneplayer: "yes",
        range: ["mid", "long"],
        stance: "no",
        charge: "no",
        gameplan: ["frametrap", "highlow"],
        setplay: "oki",
        projectile: "standard",
        reversal: "metered",
        resource: "no",
        vortex: ["neutral", "projectile"],
        difficulty: "easy",
        design: "mixed",
        archetype: ["zoners", "setplay"],
        score: 0
    },
    harddizzy: {
        name: "Hard Dizzy",
        image: "https://www.dustloop.com/wiki/images/3/33/GGXRD-R_Dizzy_Portrait.png",
        playstyle: "specialist",
        moral_system: "good",
        gender: "female",
        favourite: "neutral",
        important: ["damage", "all_rounder"],
        zoning: 1.0,
        rushdown: 0.0,
        oneplayer: "yes",
        range: ["mid", "long"],
        stance: "no",
        charge: "no",
        gameplan: ["frametrap", "highlow"],
        setplay: "oki",
        projectile: "standard",
        reversal: "metered",
        resource: "no",
        vortex: ["neutral", "projectile"],
        difficulty: "hard",
        design: "mixed",
        archetype: ["zoners", "setplay"],
        score: 0
    },
    venom: {
        name: "Venom",
        image: "https://www.dustloop.com/wiki/images/d/df/GGST_Venom_Portrait.png",
        playstyle: "specialist",
        moral_system: "neutral",
        gender: "male",
        favourite: ["pressure", "neutral"],
        important: ["all_rounder", "utility"],
        zoning: 1.0,
        rushdown: 0.0,
        oneplayer: "no",
        range: "all",
        stance: "no",
        charge: "yes",
        gameplan: ["frametrap", "risc"],
        setplay: ["oki", "neutral"],
        projectile: "standard",
        reversal: "metered",
        resource: "no",
        vortex: "neutral",
        difficulty: "medium",
        design: "mixed",
        archetype: ["zoners", "setplay"],
        score: 0
    },
    unika: {
        name: "Unika",
        image: "https://www.dustloop.com/wiki/images/7/7b/GGST_Unika_Portrait.png",
        playstyle: "prepared",
        moral_system: "good",
        gender: "female",
        favourite: ["pressure", "combos"],
        important: ["damage", "all_rounder"],
        zoning: 0.50,
        rushdown: 0.75,
        oneplayer: "sometimes",
        range: "all",
        stance: "yes",
        charge: "no",
        gameplan: ["frametrap", "highlow"],
        setplay: "no",
        projectile: "standard",
        reversal: "meterless",
        resource: "no",
        vortex: "neutral",
        difficulty: "easy",
        design: "mixed",
        archetype: "balanced",
        score: 0
    },
    lucy: {
        name: "Lucy",
        image: "https://www.dustloop.com/wiki/images/3/3b/GGST_Lucy_Portrait.png",
        playstyle: "prepared",
        moral_system: "neutral",
        gender: "female",
        favourite: ["neutral", "combos"],
        important: ["utility", "mobility"],
        zoning: 0.25,
        rushdown: 0.75,
        oneplayer: "no",
        range: ["mid", "close"],
        stance: "no",
        charge: "no",
        gameplan: ["highlow", "frametrap"],
        setplay: "no",
        projectile: "standard",
        reversal: "meterless",
        resource: "no",
        vortex: "lots",
        difficulty: "easy",
        design: "serious",
        archetype: "balanced",
        score: 0
    },
    jam: {
        name: "Jam Kuradoberi",
        image: "https://www.dustloop.com/wiki/images/5/51/GGST_Jam_Kuradoberi_Portrait.png",
        playstyle: "rewarding",
        moral_system: "good",
        gender: "female",
        favourite: ["pressure", "combos"],
        important: ["damage", "mobility"],
        zoning: 0.0,
        rushdown: 1.0,
        oneplayer: "yes",
        range: ["mid", "close"],
        stance: "yes",
        charge: "no",
        gameplan: "highlow",
        setplay: "no",
        projectile: "no",
        reversal: "meterless",
        resource: "ammo",
        vortex: "lots",
        difficulty: "easy",
        design: "mixed",
        archetype: "rushdown",
        score: 0
    },


    giovanna: {
        name: "Giovanna",
        image: "https://www.dustloop.com/wiki/images/3/3f/GGST_Giovanna_Portrait.png",
        playstyle: "prepared",
        moral_system: "neutral",
        gender: "female",
        favourite: ["pressure"],
        important: ["mobility", "all_rounder"],
        zoning: 0.0,
        rushdown: 1.0,
        oneplayer: "sometimes",
        range: "close",
        stance: "no",
        charge: "no",
        gameplan: ["frametrap", "risc"],
        setplay: "no",
        projectile: "no",
        reversal: ["meterless", "metered"],
        resource: "no",
        vortex: "neutral",
        difficulty: "easy",
        design: "mixed",
        archetype: "rushdown",
        score: 0
    }
}

function reset_characters() {
    for (var char in characters) {
        characters[char].score = 0;
    }
}
function check_characters(result) {
    for (var char in characters) {
        if (typeof(characters[char][result.key]) === "number") {
            check_numbers(char, result);
        } else {
            check_strings(char, result);
        }
    }
}

function check_strings(char, result) {
    if (characters[char][result.key].includes(result.id) || result.id === "none") {
        characters[char].score += result.amount;
    }
}

function check_numbers(char, result) {
    multiplier = result.amount;
    if (result.id === "none") {
        return;
    } else if (result.id === "no") {
        multiplier *= -1;
    }
    characters[char].score += multiplier * characters[char][result.key];
}

function check_winner() {
    var winners = [];
    for (var char in characters) {
        winners.push({score: characters[char].score, name: characters[char].name, image: characters[char].image}); 
    }
    winners.sort((a, b) => b.score - a.score);
    return winners;
}


